#!/usr/bin/env python3
"""Materialize a configured workspace from interview answers.

  uv run --with pyyaml init_workspace.py --answers /tmp/answers.json [--force]

Answers are a partial config: any subset of the schema in
config/outbound.example.yaml. They are deep-merged OVER the example, so a field
the operator did not mention keeps its documented default instead of vanishing.

Writes: config/outbound.yaml, CLAUDE.md, data/, positioning stubs, the database.
Never touches an existing config without --force.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import pathlib
import re
import sqlite3
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parents[4]
sys.path.insert(0, str(ROOT))

from lib import db  # noqa: E402

EXAMPLE = ROOT / "config" / "outbound.example.yaml"
TARGET = ROOT / "config" / "outbound.yaml"
CLAUDE_MD = ROOT / "CLAUDE.md"
DEMO = ROOT / "demo"


def _existing_created_at() -> str | None:
    """Preserve the original creation stamp across regenerations.

    Regenerating CLAUDE.md happens on every config change, and a createdAt that
    moves each time would make the workspace look newly built every edit.
    """
    if not CLAUDE_MD.exists():
        return None
    m = re.search(r'^createdAt:\s*"([^"]+)"', CLAUDE_MD.read_text(), re.M)
    return m.group(1) if m else None

# demo file -> live destination. The demo ships outside the live paths so an
# imported workspace is unmistakably un-onboarded rather than pre-filled with
# someone else's ICP.
DEMO_FILES = {
    "outbound.yaml": "config/outbound.yaml",
    "prospects.csv": "data/prospects.csv",
    "positioning/positioning.md": "positioning/positioning.md",
    "positioning/use-cases.json": "positioning/use-cases.json",
    "positioning/voice-samples.md": "positioning/voice-samples.md",
}

HEADER = """\
# =============================================================================
# Outbound configuration for {company}
# Generated by the agent-onboarding skill. Safe to hand-edit.
#
# Field documentation lives in config/outbound.example.yaml.
# After ANY edit, re-validate:
#   uv run --with pyyaml \\
#     skills/agent-onboarding/scripts/validate_config.py config/outbound.yaml
# =============================================================================

"""


def deep_merge(base: dict, over: dict) -> dict:
    """Recursive merge. Lists are REPLACED, not concatenated.

    Replacing matters: a team narrowing their ICP from four tiers to two must
    get two, not six.
    """
    out = dict(base)
    for k, v in (over or {}).items():
        if isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = deep_merge(out[k], v)
        else:
            out[k] = v
    return out


def render_claude_md(cfg: dict) -> str:
    """Generate standing instructions from config.

    Regenerated rather than hand-maintained so the agent's instructions can
    never drift from the config the code actually reads.
    """
    g = lambda p, d=None: _get(cfg, p, d)

    company = g("company.name", "the company")
    product = g("company.product_name", company)
    operator = g("operator.name", "the operator")
    op_email = g("operator.email", "")
    tz = g("operator.timezone", "UTC")

    senders = g("senders", []) or []
    sender_lines = "\n".join(
        f"  - `{s.get('id')}` {s.get('email')}: {s.get('daily_email_cap')}/day"
        f"{' (warming)' if s.get('status') == 'warming' else ''}"
        f"{' (PAUSED)' if s.get('status') == 'paused' else ''}"
        for s in senders) or "  - none configured yet"

    tiers = g("icp.tiers", []) or []
    tier_lines = "\n".join(
        f"  - **{t.get('id')}: {t.get('name')}** ({t.get('mix_pct','?')}% of intake)"
        + ("  _warm intro only, never outbound_" if t.get("outbound_allowed") is False else "")
        for t in tiers) or "  - none configured yet"

    dq_lines = "\n".join(
        f"  - {d.get('id')}: {d.get('rule')}"
        for d in (g("icp.disqualifiers", []) or [])) or "  - none configured"

    buyer_lines = "\n".join(
        f"  - **Tier {b.get('id')} ({b.get('label')})**: {', '.join(b.get('titles', [])[:8])}"
        for b in (g("icp.buyer_tiers", []) or [])) or "  - none configured"

    steps = g("cadence.steps", []) or []
    step_lines = "\n".join(
        f"  - Day {s.get('day')}: {s.get('channel')}, {s.get('intent','')}"
        + (f" _(only if {s['condition']})_" if s.get("condition") else "")
        for s in steps) or "  - none configured"

    adapters = g("adapters", {}) or {}

    def _tag(slot, name):
        p = ROOT / "adapters" / str(slot) / f"{name}.py"
        if p.exists() and '"scaffold": True' in p.read_text():
            return f"{name} (scaffold: fails closed until implemented)"
        return str(name)

    adapter_lines = "\n".join(
        f"  - `{slot}`: "
        + (" then ".join(_tag(slot, n) for n in v) if isinstance(v, list)
           else _tag(slot, v))
        for slot, v in adapters.items())

    forbidden = g("company.forbidden_names", []) or []
    forbidden_line = (", ".join(f"`{n}`" for n in forbidden)
                      if forbidden else "none declared")

    cta_type = g("message_standards.cta.type", "meeting")
    cta = (f"the self-serve link {g('message_standards.cta.url','')} (free, no card)"
           if cta_type == "self_serve"
           else f'a specific meeting ask: "{g("message_standards.meeting_ask", "15 min this week?")}"')

    escalate_lines = "\n".join(
        f"  - `{t}`" for t in (g("escalation.escalate_on", []) or [])) or "  - none configured"
    quiet_hours = g("escalation.quiet_hours_local")
    quiet_line = (f"**Quiet hours:** {quiet_hours} {tz}. Routine notifications wait until\n"
                  f"the window opens. **Escalations never wait**, at any hour."
                  if quiet_hours else
                  "**Quiet hours:** none configured, so routine notifications go out as\n"
                  "they happen. Escalations are never held back regardless.")

    notify_note = ""
    if adapters.get("notify") == "none":
        notify_note = ("\n**The `notify` adapter is `none`, so none of the above is actually\n"
                       "delivered.** Raise anything on the escalation list in the session\n"
                       "instead, and tell the operator plainly that the channel is not wired\n"
                       "rather than letting silence look like a quiet day.\n")

    banned_lines = "\n".join(
        f'  - "{b}"' for b in (g("voice.banned_phrases", []) or [])) or "  - none configured"

    dnt = g("do_not_touch", {}) or {}
    dnt_lines = "\n".join(
        f"  - **{label}:** "
        + (", ".join(f"`{x}`" for x in (dnt.get(key) or [])) or "(none listed)")
        for key, label in (("companies", "Companies"), ("domains", "Domains"),
                           ("people", "People"), ("geos", "Geos")))

    sender_note = ""
    if adapters.get("sender") == "dryrun":
        sender_note = ("\n> **This workspace is in DRY RUN.** Drafts are produced and logged, "
                       "nothing is sent. Switch `adapters.sender` only after the operator has "
                       "reviewed dry-run output and approved.\n")

    # The frontmatter is the agent's identity in the .agent workspace format,
    # so it has to survive regeneration. Without it the file still reads fine
    # but the workspace stops being re-exportable as a template.
    created = _existing_created_at() or dt.datetime.now(
        dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.000Z")

    # json.dumps, not bare interpolation: a company name containing a colon or
    # a quote would otherwise emit frontmatter that does not parse as YAML.
    fm_name = json.dumps(f"Outbound Campaign Agent: {company}")
    fm_desc = json.dumps(
        f"Runs personalized outbound for {company}: ICP qualification, "
        f"enrichment, fail-closed suppression, linted drafting, capped sending, "
        f"cadence, reply detection, and calendar-sourced meeting reporting.")

    return f"""---
name: {fm_name}
description: {fm_desc}
createdAt: "{created}"
---

# Outbound Agent: {company}

You run end-to-end personalized outbound for {company}. You research prospects,
qualify them against the ICP, enrich for contact data, draft a personalized
opener tied to a concrete workflow the prospect owns, send, run the follow-up
cadence, detect replies, and report performance.

**All behavior is driven by `config/outbound.yaml`.** That file is the single
source of truth. If this document and the config disagree, the config wins and
you should regenerate this file. Never hardcode a company name, cap, ICP rule,
or vendor choice into a script.
{sender_note}
## Identity

- **Company:** {company}
- **Product name in prospect-facing copy:** {product}
- **Names you must NEVER use in prospect-facing copy:** {forbidden_line}
- **Operator:** {operator} ({op_email})
- **Timezone:** {tz}

## Senders and caps

{sender_lines}

- **Intake ceiling:** {g("limits.new_prospects_per_day", "?")} net-new prospects/day
- **Send days:** {", ".join(str(d) for d in (g("limits.send_days", []) or []))}
- **Send window:** {g("limits.send_window_local", "?")} {tz}

Caps are per sender per day and are hard. Per-campaign rates STACK, so the
governor sums intended volume across all campaigns before any send. If the
operator asks to raise a cap, that is an approval gate, not a config edit you
make on your own.

## Adapters

{adapter_lines}

Vendors are swappable modules under `adapters/<slot>/`. The motion does not
change when a vendor does. Never call a vendor API directly from a skill script;
go through the adapter so the swap stays clean.

## ICP

- **Outbound size band:** {g("icp.employee_range", "?")} employees
- **Geos:** {", ".join(str(x) for x in (g("icp.geos", []) or [])) or "unrestricted"}

{tier_lines}

**Hard disqualifiers:**
{dq_lines}

**Buyer map:**
{buyer_lines}

Lead with Tier {g("icp.lead_with_tier", "B")}. Include the decision maker for
awareness, but do not blast every tier at one company on the same day. Max
{g("icp.max_contacts_per_company", "?")} contacts per company, at least
{g("icp.min_days_between_same_company_touches", "?")} day(s) apart.

If a prospect falls outside ICP, flag it and ask the operator rather than
burning a send.

## Positioning

- **Wedge:** {g("positioning.wedge", "(not set)")}
- **Pain:** {g("positioning.pain", "(not set)")}
- **Proof metric:** {g("positioning.proof_metric", "(not set)")}
- **We are NOT:** {", ".join(str(x) for x in (g("positioning.not_a", []) or [])) or "(not set)"}

Read `{g("positioning.positioning_file", "positioning/positioning.md")}` and
`{g("positioning.use_cases_file", "positioning/use-cases.json")}` before drafting.

## Cadence

{step_lines}

Stop the cadence immediately on any reply, even an ambiguous one. Let the
operator decide whether to re-engage.

**LinkedIn steps are manual.** There is no LinkedIn executor and you must not
automate one (LinkedIn restricts accounts for it). The flow: draft the note,
run send.py for the step to lint it and check the invite cap, the sender
performs it on LinkedIn themselves, then record it with `send.py --manual`.
Invites are capped per sender per day; the 300-character invite ceiling is
enforced by the linter. When the operator reports an accepted invite, a
LinkedIn reply, or a no-show, record it immediately with `mark.py`.

## Operations loop

The motion only runs if something ticks it:

- **Cadence tick** ({g("reporting.schedule.cadence_tick_cron", "0 9 * * 2-4")},
  operator timezone): `tick.py` checks replies, surfaces due follow-ups and the
  manual LinkedIn queue. It sends nothing on its own.
- **Weekly digest** ({g("reporting.schedule.weekly_report_cron", "0 15 * * 5")}):
  run `meetings.py` first so the outcome number is fresh, then
  `weekly_report.py --send`.

If these are not on the platform scheduler yet, offer to schedule them. A
configured motion with no heartbeat is a manual process with extra steps.

**The live dashboard** (slug `outbound`, under `/workspace/artifacts/`) is the
operator's monitor-and-approve surface: the approval queue with Approve and
Reject buttons on top, deliverability and outcomes below. Keep it fresh with
`report.py --write-dashboard` on every tick, and keep it running; if it is not
built yet, copy `dashboard/index.js` and `dashboard/package.json` into the
platform dashboard slot and start it.

## Approval queue

Any draft that needs a human sends only after a human decides: every draft of
a first batch, anything below the confidence threshold, anything out of
pattern. Stage those with `queue.py add` (it lints first) and point the
operator at the dashboard; record chat decisions with `queue.py
approve/reject`. Both surfaces write the same table and the same audit rows.
`send.py` refuses pending or rejected drafts and sends an approved draft only
as the exact copy that was approved. Approving is not sending: every gate
still runs.

## Message standards

Every Day-0 opener must:

1. Name a specific observation about the prospect's role, company, or recent
   activity. Not "I noticed you're VP of Ops at X."
2. Map to one concrete workflow from the use-cases file that they would
   plausibly own.
3. Lead with the positioning wedge and support it with "{g("positioning.proof_metric", "")}".
4. Carry a single low-friction ask: {cta}
5. Stay under {g("message_standards.max_words", 90)} words.
6. Use a subject under {g("message_standards.max_subject_chars", 40)} chars. No
   clickbait, no all-caps, no emojis.
7. Contain NO em dashes or en dashes. Use periods, commas, or colons.
8. Break into short paragraphs of 1 to {g("message_standards.max_sentences_per_paragraph", 3)}
   sentences separated by a blank line. Never one dense block.
9. End with the configured signature block.

These are enforced mechanically by `lib/linter.py` on every draft before send.
A draft that fails the linter does not go out. Do not try to work around it;
fix the copy.

Surface any draft you are under
{int(float(g("message_standards.min_confidence_to_autosend", 0.7)) * 100)}% confident in.

## Voice

Before drafting anything, read `{g("voice.samples_file", "positioning/voice-samples.md")}`
and the notes below. Those samples are real messages the operator sent and was
happy with. They are read, never sent. The linter can enforce mechanics; only
the samples can enforce voice, and copy written without them reads like copy.

- **How the operator wants to sound:** {g("voice.notes", "(not set)")}

**Never use these phrases:**
{banned_lines}

Banned phrases are enforced by `lib/linter.py` on every draft, so there is no
point rewording around the check or arguing that this one is fine in context.
A draft containing one does not go out. Fix the line.

## Suppression

Fail-closed. If a suppression source is unreachable, the run HALTS. Emailing a
current customer as a cold prospect is worse than a delayed batch.
Suppression layers, in order: {" then ".join(str(x) for x in (g("adapters.suppression", []) or []))}.

## Do not touch

Three separate gates that get confused constantly. Keep them straight:

- **ICP** says *not a fit*.
- **Suppression** says *already engaged*.
- **Do not touch** says *never, and fit is irrelevant*.

The do-not-touch list is checked before every send and is fail-closed like
suppression. Current entries:

{dnt_lines}

Fit is not the question here, so never argue an entry back into a batch because
the prospect looks good. An empty list is not proof that there are no
exclusions, only that nobody has been asked yet: if the lists are empty, ask the
operator before the first batch. Adding or removing an entry is the operator's
call, never yours.

## Escalation

- **Routine output** (drafts for approval, batch summaries, the weekly report)
  goes to `{g("escalation.digest_to", "(not set)")}`.
- **Interrupt a human** at `{g("escalation.escalate_to", "(not set)")}` for:

{escalate_lines}

{quiet_line}
{notify_note}
## Reporting

Never show a rate without its denominator. Suppress any rate whose denominator
is below {g("reporting.n_floor", 10)} and show the raw count instead.

**Do not track opens.** Open tracking is unreliable and the pixel hurts
deliverability for low-volume senders.

## Approval gates: never automate these

- First batch of any new campaign
- New template copy
- New campaign activation
- Any cap increase
- Any send to a prospect outside ICP

After the operator approves the pattern for
{g("approval_gates.auto_proceed_after_approved", 3)} prospects, you may proceed
unattended for the rest of that batch, but must still surface low-confidence drafts.

## First run

Goal: {g("first_run.goal", "(not set)")}

It is a dry run of {g("first_run.batch_size", "?")} prospects. Source, qualify,
enrich, draft, log, send nothing. The operator reads the real output before
anything ships, and that review is not something you can waive, infer from
silence, or mark satisfied on their behalf. A first run nobody read is how a
misconfigured ICP becomes a hundred wrong emails.

## Response style

Be specific and complete. Verify your own work. Never hallucinate: say "I don't
know" when you don't. Attach explicit confidence levels (high/moderate/low/
unknown) to factual claims, draft-quality estimates, and ICP-fit assessments.

Do not validate the operator before answering. If they are wrong, say so
immediately with the reason, and lead with the strongest counterargument. Do not
capitulate on pushback without new evidence. Accuracy and reply rate are the
success metrics, not operator approval.
"""


def _get(d: dict, dotted: str, default=None):
    node = d
    for part in dotted.split("."):
        if not isinstance(node, dict) or part not in node:
            return default
        node = node[part]
    return node


def _rel(p: pathlib.Path) -> str:
    """Template-relative path for printing, tolerant of absolute config values."""
    try:
        return str(p.relative_to(ROOT))
    except ValueError:
        return str(p)


POSITIONING_MD = """# Positioning: {company}

> Generated stub. Replace every placeholder before the first send. An opener
> built on an empty positioning file reads as generic praise.

## Wedge

{wedge}

## The pain we name

{pain}

## What we are NOT

{not_a}

## Proof

{proof}

## Messaging framework

Hook: the specific observation about this prospect.
Bridge: why that observation implies the pain above.
Solution: the one concrete workflow they would own.
Proof: the quantifier, once.

## Objection handlers

- "We already have a tool for that." →
- "No budget right now." →
- "Send me some information." →
"""

USE_CASES_STUB = [
    {
        "id": "example-ops-handoff",
        "name": "EXAMPLE: Replace with a real use case",
        "personas": ["Head of Operations", "Operations Manager"],
        "industries": ["*"],
        "overview": "One or two sentences describing the recurring workflow.",
        "spotlight": "The single most painful step, in the buyer's own words.",
        "sample_agents": [
            "A concrete thing you would automate for them.",
            "A second concrete thing.",
        ],
        "hours_saved_per_week": 10,
        "why_it_works": "Why this lands with this persona specifically.",
    }
]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--answers", help="JSON file of interview answers (partial config)")
    ap.add_argument("--force", action="store_true",
                    help="overwrite an existing config/outbound.yaml")
    ap.add_argument("--skip-claude-md", action="store_true")
    ap.add_argument("--regen-claude-md", action="store_true",
                    help="rewrite CLAUDE.md from the existing config and exit; "
                         "touches no config, no database, no positioning files")
    ap.add_argument("--demo", action="store_true",
                    help="load the worked Northwind Logistics example so the whole "
                         "motion can be run before any interview happens")
    args = ap.parse_args()

    if args.demo:
        if TARGET.exists() and not args.force:
            print(f"{TARGET.relative_to(ROOT)} already exists; --demo would overwrite "
                  f"it. Re-run with --force if that is what you want.", file=sys.stderr)
            return 1
        for src_rel, dst_rel in DEMO_FILES.items():
            dst = ROOT / dst_rel
            dst.parent.mkdir(parents=True, exist_ok=True)
            dst.write_bytes((DEMO / src_rel).read_bytes())

        # The demo has to be reproducible: a leftover database makes the second
        # run suppress every prospect the first run stored, which reads as a
        # broken pipeline. Refuse rather than delete anything with real sends.
        db_path = ROOT / _get(yaml.safe_load(TARGET.read_text()),
                              "adapter_config.sqlite.path", "data/campaigns.db")
        if db_path.exists():
            n = sqlite3.connect(db_path).execute(
                "SELECT COUNT(*) FROM sqlite_master WHERE name='sends'").fetchone()[0]
            sends = (sqlite3.connect(db_path).execute(
                "SELECT COUNT(*) FROM sends").fetchone()[0] if n else 0)
            if sends:
                print(f"{db_path.relative_to(ROOT)} has {sends} logged send(s). "
                      f"Refusing to reset it. Move it aside first if you want a "
                      f"clean demo.", file=sys.stderr)
                return 1
            db_path.unlink()
        db.init(db_path)
        CLAUDE_MD.write_text(render_claude_md(yaml.safe_load(TARGET.read_text())))
        print("Loaded the Northwind Logistics demo. Sender is 'dryrun'.\n"
              "  uv run --with pyyaml .claude/skills/outbound-campaign/scripts/pipeline.py\n"
              "Run onboarding with --force when you want your own config.")
        return 0

    # CLAUDE.md is derived, so it goes stale every time the config is edited by
    # hand. Without this it could only be refreshed by re-running onboarding.
    if args.regen_claude_md:
        if not TARGET.exists():
            print(f"no {TARGET.relative_to(ROOT)} to render from; run onboarding first",
                  file=sys.stderr)
            return 1
        (ROOT / "CLAUDE.md").write_text(
            render_claude_md(yaml.safe_load(TARGET.read_text())))
        print(f"regenerated CLAUDE.md from {TARGET.relative_to(ROOT)}")
        return 0

    if TARGET.exists() and not args.force:
        print(f"refusing to overwrite existing {TARGET.relative_to(ROOT)} (use --force)",
              file=sys.stderr)
        return 1

    base = yaml.safe_load(EXAMPLE.read_text())
    answers = {}
    if args.answers:
        p = pathlib.Path(args.answers)
        if not p.exists():
            print(f"answers file not found: {p}", file=sys.stderr)
            return 2
        answers = json.loads(p.read_text())
        if not isinstance(answers, dict):
            print("answers must be a JSON object", file=sys.stderr)
            return 2

    cfg = deep_merge(base, answers)
    company = _get(cfg, "company.name", "your company")

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(
        HEADER.format(company=company)
        + yaml.safe_dump(cfg, sort_keys=False, allow_unicode=True, width=88)
    )
    written = [TARGET]

    for rel in ("data", "data/dry-runs", "positioning", "docs"):
        (ROOT / rel).mkdir(parents=True, exist_ok=True)

    db_path = _get(cfg, "adapter_config.sqlite.path", "data/campaigns.db")
    conn = db.init(ROOT / db_path)
    conn.close()
    written.append(ROOT / db_path)

    pos_md = ROOT / str(_get(cfg, "positioning.positioning_file",
                             "positioning/positioning.md"))
    if not pos_md.exists():
        pos_md.parent.mkdir(parents=True, exist_ok=True)
        pos_md.write_text(POSITIONING_MD.format(
            company=company,
            wedge=_get(cfg, "positioning.wedge", "(TODO)"),
            pain=_get(cfg, "positioning.pain", "(TODO)"),
            not_a=", ".join(str(x) for x in (_get(cfg, "positioning.not_a", []) or []))
                  or "(TODO)",
            proof=_get(cfg, "positioning.proof_metric", "(TODO)"),
        ))
        written.append(pos_md)

    uc = ROOT / str(_get(cfg, "positioning.use_cases_file", "positioning/use-cases.json"))
    if not uc.exists():
        uc.parent.mkdir(parents=True, exist_ok=True)
        uc.write_text(json.dumps(USE_CASES_STUB, indent=2) + "\n")
        written.append(uc)

    for rel, content in (("data/seen.json", "[]\n"),
                         ("data/blocklist_domains.json", "[]\n")):
        p = ROOT / rel
        if not p.exists():
            p.write_text(content)
            written.append(p)

    # Voice samples are the highest-leverage thing the operator provides and the
    # easiest to skip, so seed the file with the shipped example to fill in.
    notes: list[str] = []
    voice_target = ROOT / str(_get(cfg, "voice.samples_file", "positioning/voice-samples.md"))
    voice_example = ROOT / "positioning" / "voice-samples.example.md"
    if voice_target.exists():
        pass
    elif voice_example.exists():
        voice_target.parent.mkdir(parents=True, exist_ok=True)
        voice_target.write_text(voice_example.read_text())
        written.append(voice_target)
    else:
        notes.append(f"no {voice_example.name} to copy; create "
                     f"{_rel(voice_target)} by hand before the first draft")

    if not args.skip_claude_md:
        CLAUDE_MD.write_text(render_claude_md(cfg))
        written.append(CLAUDE_MD)

    print(f"Configured workspace for {company}\n")
    for p in written:
        print(f"  wrote  {_rel(p)}")
    for n in notes:
        print(f"  note   {n}")

    print("\nNext:")
    print("  1. uv run --with pyyaml skills/agent-onboarding/scripts/validate_config.py "
          "config/outbound.yaml")
    print("  2. uv run --with pyyaml skills/agent-onboarding/scripts/selftest.py")
    print(f"  3. Fill in {_rel(uc)} with real use cases before drafting.")
    print(f"  4. Paste 1-3 real emails the operator has sent into {_rel(voice_target)}. "
          "Without them the drafts read like copy, not like the operator.")
    print("  5. Fill in `do_not_touch` in config/outbound.yaml. It ships empty, and an empty "
          "exclusion list is indistinguishable from a question nobody asked.")
    print(f"  6. Confirm `escalation.escalate_to` reaches a real human: "
          f"{_get(cfg, 'escalation.escalate_to', '(not set)')}")

    if _get(cfg, "adapters.notify") == "none":
        print("\n  NOTE: notify is 'none'. Nothing in `escalation` can be delivered; "
              "escalations have to be raised in-session.")
    if _get(cfg, "adapters.sender") == "dryrun":
        print("\n  NOTE: sender is 'dryrun'. Nothing will be sent until you change it.")
    print(f"\n  First run is a dry run of {_get(cfg, 'first_run.batch_size', '?')} prospects "
          "and a human reads it before anything ships.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
