#!/usr/bin/env python3
"""Send a markdown report as a styled HTML email via the Gmail proxy.

Examples
--------
  # preview only (no send)
  uv run --env-file .env --with markdown,requests \
    .claude/skills/email-report/send_report.py \
    --md reports/seo-weekly-2026-08-03.md --preview /tmp/weekly.html

  # send
  uv run --env-file .env --with markdown,requests \
    .claude/skills/email-report/send_report.py \
    --md reports/seo-weekly-2026-08-03.md \
    --subject 'SEO weekly — 2026-08-03' \
    --to owner@example.com --summary-md /tmp/highlights.md

Sender defaults come from /workspace/seo/config.json:
  report.from_email + report.gmail_account_id (the connected Gmail account id from
  CONNECTED_ACCOUNTS), report.to (default recipient), report.brand (header label).
"""

import argparse
import base64
import json
import os
import pathlib
import sys
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from render import render  # noqa: E402

try:
    _CFG = json.loads(pathlib.Path("/workspace/seo/config.json").read_text()).get("report", {})
except Exception:
    _CFG = {}


def send(account_id, sender, to, subject, html, plain):
    import requests

    msg = MIMEMultipart("alternative")
    msg["to"] = to
    msg["from"] = sender
    msg["subject"] = subject
    msg.attach(MIMEText(plain, "plain", "utf-8"))
    msg.attach(MIMEText(html, "html", "utf-8"))

    r = requests.post(
        f"{os.environ['PROXY_BASE_URL']}/{account_id}/gmail.googleapis.com"
        "/gmail/v1/users/me/messages/send",
        headers={
            "Authorization": f"Bearer {os.environ['PROXY_TOKEN']}",
            "Content-Type": "application/json",
        },
        json={"raw": base64.urlsafe_b64encode(msg.as_bytes()).decode()},
    )
    return r


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--md", required=True, help="Markdown report file")
    p.add_argument("--to", default=_CFG.get("to"))
    p.add_argument("--subject")
    p.add_argument("--from", dest="sender", default=_CFG.get("from_email"))
    p.add_argument("--account-id", default=_CFG.get("gmail_account_id"))
    p.add_argument("--title", help="Header title (default: report's H1)")
    p.add_argument("--summary", help="Highlights as markdown text")
    p.add_argument("--summary-md", help="Highlights markdown file")
    p.add_argument("--preheader", default="", help="Inbox preview snippet")
    p.add_argument("--footer", default="", help="Footer line (HTML allowed)")
    p.add_argument("--preview", help="Write the HTML here instead of sending")
    args = p.parse_args()

    report = pathlib.Path(args.md).read_text()
    summary = args.summary or (
        pathlib.Path(args.summary_md).read_text() if args.summary_md else ""
    )
    footer = args.footer or (
        f"Generated by the SEO agent — full report: <code>{args.md}</code>"
    )
    html = render(
        report,
        title=args.title,
        summary=summary,
        preheader=args.preheader,
        footer=footer,
        brand=_CFG.get("brand") or "SEO Agent",
    )

    if args.preview:
        pathlib.Path(args.preview).write_text(html)
        print(f"Preview written: {args.preview}")
        return

    if not (args.to and args.subject):
        p.error("--to and --subject are required unless --preview is used")
    if not (args.sender and args.account_id):
        p.error("no sender configured — set report.from_email + report.gmail_account_id "
                "in seo/config.json or pass --from/--account-id")

    plain = f"{summary}\n\n---\n\n{report}" if summary else report
    r = send(args.account_id, args.sender, args.to, args.subject, html, plain)
    print(f"Status: {r.status_code}")
    d = r.json()
    print(f"Message ID: {d.get('id', 'N/A')}  Thread: {d.get('threadId', 'N/A')}")
    if r.status_code != 200:
        print(f"Error: {d}")
        sys.exit(1)


if __name__ == "__main__":
    main()
